### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by zzzzzbin** [PPPerry/Hierarchical-RL4RA#1]
Hello,PPPerry!
Could you tell me which is the paper this code based on?

**Comment by PPPerry** [comment]
@zzzzzbin 
Hierarchical Reinforcement Learning for Scarce Medical Resource Allocation with Imperfect Information (https://dl.acm.org/doi/10.1145/3447548.3467181)
and their github repo: https://github.com/KYHKL-Q/Hierarchical-RL

**Comment by PPPerry** [comment]
close

**Comment by zzzzzbin** [comment]
> @zzzzzbin Hierarchical Reinforcement Learning for Scarce Medical Resource Allocation with Imperfect Information (https://dl.acm.org/doi/10.1145/3447548.3467181) and their github repo: https://github.com/KYHKL-Q/Hierarchical-RL
Ok,thank U!
